import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { extname, join, relative, resolve, sep } from 'node:path';

const projectRoot = resolve(import.meta.dirname, '..');
const publicRoot = join(projectRoot, 'public');
const distRoot = join(projectRoot, 'dist');
const workerPath = join(distRoot, 'server', 'index.js');

const contentTypes = {
  '.css': 'text/css; charset=utf-8',
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.png': 'image/png',
};

async function listFiles(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(entries.map(async (entry) => {
    const path = join(directory, entry.name);
    return entry.isDirectory() ? listFiles(path) : [path];
  }));
  return files.flat();
}

const sourceFiles = (await listFiles(publicRoot)).sort();
const assets = await Promise.all(sourceFiles.map(async (filePath) => {
  const route = `/${relative(publicRoot, filePath).split(sep).join('/')}`;
  const body = await readFile(filePath);
  const contentType = contentTypes[extname(filePath).toLowerCase()] ?? 'application/octet-stream';
  return [route, [body.toString('base64'), contentType]];
}));

const workerSource = `// Generated by scripts/build.mjs. Do not edit directly.
const ASSETS = new Map(${JSON.stringify(assets)});

function decodeBase64(value) {
  return Uint8Array.from(atob(value), (character) => character.charCodeAt(0));
}

function resolveAssetPath(pathname) {
  let decodedPath;
  try {
    decodedPath = decodeURIComponent(pathname);
  } catch {
    return null;
  }

  if (decodedPath === '/') return '/index.html';
  if (decodedPath.endsWith('/')) return \`\${decodedPath.slice(0, -1)}.html\`;
  if (!decodedPath.split('/').at(-1).includes('.')) return \`\${decodedPath}.html\`;
  return decodedPath;
}

function responseHeaders(contentType, pathname) {
  return {
    'Cache-Control': pathname.startsWith('/assets/') ? 'public, max-age=3600' : 'no-cache',
    'Content-Security-Policy': "default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'; connect-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'",
    'Content-Type': contentType,
    'Permissions-Policy': 'camera=(), geolocation=(), microphone=()',
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'X-Content-Type-Options': 'nosniff',
    'X-Frame-Options': 'DENY',
  };
}

export default {
  async fetch(request) {
    if (request.method !== 'GET' && request.method !== 'HEAD') {
      return new Response('Method Not Allowed', { status: 405, headers: { Allow: 'GET, HEAD' } });
    }

    const requestedPath = resolveAssetPath(new URL(request.url).pathname);
    const asset = requestedPath ? ASSETS.get(requestedPath) : null;
    const fallback = ASSETS.get('/404.html');
    const [encodedBody, contentType] = asset ?? fallback;

    return new Response(request.method === 'HEAD' ? null : decodeBase64(encodedBody), {
      status: asset ? 200 : 404,
      headers: responseHeaders(contentType, asset ? requestedPath : '/404.html'),
    });
  },
};
`;

await rm(distRoot, { recursive: true, force: true });
await mkdir(join(distRoot, 'server'), { recursive: true });
await mkdir(join(distRoot, '.openai'), { recursive: true });
await writeFile(workerPath, workerSource);
await writeFile(
  join(distRoot, '.openai', 'hosting.json'),
  await readFile(join(projectRoot, '.openai', 'hosting.json')),
);

console.log(`Built ${assets.length} static assets into dist/server/index.js`);

